#!/bin/bash

#go build -o bellbox cli/main.go
if [[ $? -ne 0 ]]; then
	echo "build failed"
	exit 1
fi
cp bellbox.service /etc/systemd/system/
cp bellbox /tmp/bellbox
cp config.example.json /tmp/config.json
cp production.environment /tmp/ENV

mkdir /opt
cd /opt
mkdir bellbox
cd bellbox
mkdir bin
mv /tmp/bellbox bin/
mv /tmp/config.json .
mv /tmp/ENV .

systemctl daemon-reload
systemctl enable bellbox
systemctl start bellbox
